package subd.ui.util;
public enum QueryType {

    SELECT1, SELECT2, SELECT3, SELECT4,
    DISABLE_TRIGGER1, ENABLE_TRIGGER1,
    DISABLE_TRIGGER2,  ENABLE_TRIGGER2,
    DISABLE_TRIGGER3, ENABLE_TRIGGER3,
    ;
}
